on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          key: package-lock=${{ hashFiles('package-lock.json') }}
          path: node_modules
          restore-keys: package-lock=
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: package-lock=${{ hashFiles('package-lock.json') }}
          path: node_modules
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: package-lock=${{ hashFiles('package-lock.json') }}
          path: node_modules
      - run: npm run test
  tsc:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: package-lock=${{ hashFiles('package-lock.json') }}
          path: node_modules
      - run: npm run tsc
  cypress:
    runs-on: ubuntu-16.04
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: package-lock=${{ hashFiles('package-lock.json') }}
          path: node_modules
      - uses: cypress-io/github-action@v1
        with:
          start: npm start
          record: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
